COLORS = [
    "cyan",
    "purple",
    "blue",
    "green",
    "yellow",
    "orange",
    "red",
    'violet'
]
FONT_STYLE = ("Courier", 20, "normal")
SCREEN_WIDTH = 660
SCREEN_HEIGHT = 750
BRICK_WIDTH = 80
BRICK_HEIGHT = 20
PADDLE_WIDTH = 100
PADDLE_HEIGHT = 20
BALL_WIDTH = 20
BALL_HEIGHT = 20
PADDING = 75
TOP_BORDER = int(SCREEN_HEIGHT / 2)
BOTTOM_BORDER = int(-SCREEN_HEIGHT / 2)
LEFT_BORDER = int(-SCREEN_WIDTH/2)
RIGHT_BORDER = int(SCREEN_WIDTH/2)
TOP_BORDER_BRICKS = int(TOP_BORDER - 150)
BOTTOM_BORDER_BRICKS = int(TOP_BORDER_BRICKS - 7 * BRICK_HEIGHT)
LEFT_BORDER_BRICKS = int(LEFT_BORDER + PADDING + BRICK_WIDTH/2)
RIGHT_BORDER_BRICKS = int(RIGHT_BORDER - PADDING - BRICK_WIDTH/2)
DIST_PADDLE_BORDER = int(RIGHT_BORDER - PADDLE_WIDTH/2)
BALL_SPEED = 0.04

PADDLE_SPEED = PADDLE_WIDTH
while DIST_PADDLE_BORDER % PADDLE_SPEED != 0:
    PADDLE_SPEED -= 10
    if PADDLE_SPEED < 0:
        PADDLE_SPEED = PADDLE_WIDTH
        break
